version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rphqgmebrF1
    ports:
      - '3306:3306' # Maps port 3306 of the container to port 3306 on the host
